# Database settings.
database:

  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: 

  # the JDBC URL
  url: jdbc:mysql://127.0.0.1:3306
